# Generated by Django 5.1.1 on 2025-07-18 07:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
