# Generated by Django 5.1.1 on 2025-07-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0003_alter_district_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirepointUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_type', models.CharField(choices=[('excel', 'Excel File'), ('json', 'GeoJSON'), ('shp', 'Shapefile')], max_length=10)),
                ('data_file', models.FileField(upload_to='firepoint_uploads/')),
                ('shp_file', models.FileField(blank=True, null=True, upload_to='shapefiles/')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
