# Generated by Django 5.1.1 on 2025-07-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0004_firepointupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('firepoint', 'Fire Points'), ('province', 'Provinces'), ('district', 'Districts')], max_length=10)),
                ('upload_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'GeoJSON'), ('shp', 'Shapefile')], max_length=10)),
                ('data_file', models.FileField(upload_to='geodata_uploads/')),
                ('auxiliary_file', models.FileField(blank=True, null=True, upload_to='geodata_auxiliary/')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FirepointUpload',
        ),
    ]
