# Generated by Django 5.1.1 on 2025-07-31 17:31

import Firetracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0005_geodataupload_delete_firepointupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['admin1Name', 'admin2Name'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='firepoint',
            options={'ordering': ['-acq_date'], 'verbose_name': 'Fire Point', 'verbose_name_plural': 'Fire Points'},
        ),
        migrations.AlterModelOptions(
            name='geodataupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Geo Data Upload', 'verbose_name_plural': 'Geo Data Uploads'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['admin1Name'], 'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
        migrations.RemoveField(
            model_name='geodataupload',
            name='auxiliary_file',
        ),
        migrations.AddField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='firepoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='firepoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='geodataupload',
            name='auxiliary_files',
            field=models.FileField(blank=True, help_text='For Shapefiles, upload a ZIP containing all required files (.shp, .shx, .dbf, etc.)', null=True, upload_to='geodata_auxiliary/'),
        ),
        migrations.AddField(
            model_name='geodataupload',
            name='processing_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geodataupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='province',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='geodataupload',
            name='data_file',
            field=models.FileField(upload_to='geodata_uploads/', validators=[Firetracker.models.validate_file_extension]),
        ),
    ]
