# Generated by Django 5.1.1 on 2025-07-31 17:55

import Firetracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0006_alter_district_options_alter_firepoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodataupload',
            name='processing_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geodataupload',
            name='records_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geodataupload',
            name='auxiliary_files',
            field=models.FileField(blank=True, help_text='For Shapefiles, upload a ZIP containing all required files (.shp, .shx, .dbf, etc.)', null=True, upload_to='geodata_auxiliary/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='geodataupload',
            name='data_file',
            field=models.FileField(upload_to='geodata_uploads/%Y/%m/%d/', validators=[Firetracker.models.validate_file_extension]),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['admin2Pcod'], name='Firetracker_admin2P_9322e1_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['admin1Name'], name='Firetracker_admin1N_4bd45c_idx'),
        ),
        migrations.AddIndex(
            model_name='firepoint',
            index=models.Index(fields=['acq_date'], name='Firetracker_acq_dat_92f46f_idx'),
        ),
        migrations.AddIndex(
            model_name='firepoint',
            index=models.Index(fields=['confidence'], name='Firetracker_confide_00d987_idx'),
        ),
        migrations.AddIndex(
            model_name='geodataupload',
            index=models.Index(fields=['data_type'], name='Firetracker_data_ty_496e20_idx'),
        ),
        migrations.AddIndex(
            model_name='geodataupload',
            index=models.Index(fields=['processed'], name='Firetracker_process_3391b7_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['admin1Pcod'], name='Firetracker_admin1P_0a9fa0_idx'),
        ),
    ]
