# Generated by Django 5.1.1 on 2025-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0007_geodataupload_processing_errors_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='district',
            name='Firetracker_admin2P_9322e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='district',
            name='Firetracker_admin1N_4bd45c_idx',
        ),
        migrations.RemoveIndex(
            model_name='firepoint',
            name='Firetracker_acq_dat_92f46f_idx',
        ),
        migrations.RemoveIndex(
            model_name='firepoint',
            name='Firetracker_confide_00d987_idx',
        ),
        migrations.RemoveIndex(
            model_name='geodataupload',
            name='Firetracker_data_ty_496e20_idx',
        ),
        migrations.RemoveIndex(
            model_name='geodataupload',
            name='Firetracker_process_3391b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='Firetracker_admin1P_0a9fa0_idx',
        ),
        migrations.RemoveField(
            model_name='geodataupload',
            name='auxiliary_files',
        ),
        migrations.AlterField(
            model_name='geodataupload',
            name='upload_format',
            field=models.CharField(choices=[('json', 'GeoJSON'), ('shp', 'Shapefile')], max_length=10),
        ),
    ]
