# Generated by Django 5.1.1 on 2025-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0008_remove_district_firetracker_admin2p_9322e1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataupload',
            name='upload_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('json', 'GeoJSON'), ('shp', 'Shapefile')], max_length=10),
        ),
    ]
