# Generated by Django 5.1.1 on 2025-08-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0009_alter_geodataupload_upload_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Firetracker.province'),
        ),
        migrations.AlterField(
            model_name='district',
            name='admin2Pcod',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='firepoint',
            name='brightness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firepoint',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firepoint',
            name='frp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='admin1Pcod',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
