# Generated by Django 5.1.1 on 2025-08-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0010_district_province_alter_district_admin2pcod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='admin1Pcod',
            field=models.CharField(max_length=20),
        ),
    ]
