# Generated by Django 5.1.1 on 2025-08-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0011_alter_province_admin1pcod'),
    ]

    operations = [
    ]
