# Generated by Django 5.1.1 on 2025-08-01 11:36

import Firetracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0012_auto_20250801_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firepoint',
            name='confidence',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100')], null=True),
        ),
        migrations.AlterField(
            model_name='geodataupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='geodataupload',
            name='data_file',
            field=models.FileField(help_text='Upload data file in the selected format', upload_to='geodata_uploads/%Y/%m/%d/', validators=[Firetracker.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='geodataupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='admin1Pcod',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['admin2Pcod'], name='Firetracker_admin2P_9322e1_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['admin1Name'], name='Firetracker_admin1N_4bd45c_idx'),
        ),
        migrations.AddIndex(
            model_name='firepoint',
            index=models.Index(fields=['acq_date'], name='Firetracker_acq_dat_92f46f_idx'),
        ),
        migrations.AddIndex(
            model_name='firepoint',
            index=models.Index(fields=['latitude', 'longitude'], name='Firetracker_latitud_61780c_idx'),
        ),
        migrations.AddIndex(
            model_name='geodataupload',
            index=models.Index(fields=['data_type'], name='Firetracker_data_ty_496e20_idx'),
        ),
        migrations.AddIndex(
            model_name='geodataupload',
            index=models.Index(fields=['processed'], name='Firetracker_process_3391b7_idx'),
        ),
        migrations.AddIndex(
            model_name='geodataupload',
            index=models.Index(fields=['created_at'], name='Firetracker_created_51dad4_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['admin1Pcod'], name='Firetracker_admin1P_0a9fa0_idx'),
        ),
    ]
