# Generated by Django 5.1.1 on 2025-08-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firetracker', '0013_alter_firepoint_confidence_and_more'),
    ]

    operations = [
    ]
