services:
  - type: web
    name: firetracker-web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Firetracker-backendd.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: firetracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"