services:
  - type: web
    name: firetracker-web
    runtime: python
    pythonVersion: "3.10.13"
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: "gunicorn Firetracker-backendd.wsgi:application"
    envVars:
      - key: GDAL_LIBRARY_PATH
        value: "/usr/lib/x86_64-linux-gnu/libgdal.so.32"
      - key: GEOS_LIBRARY_PATH
        value: "/usr/lib/x86_64-linux-gnu/libgeos_c.so.1"
      - key: PROJ_LIB
        value: "/usr/share/proj"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_HOST
        fromDatabase:
          name: firetracker-db
          property: host
      - key: DB_PASSWORD
        fromDatabase:
          name: firetracker-db
          property: password