services:
  - type: web
    name: firetracker-web
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: GDAL_LIBRARY_PATH
        value: "/usr/lib/libgdal.so"
      - key: GEOS_LIBRARY_PATH
        value: "/usr/lib/libgeos_c.so"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: DB_NAME
        fromDatabase:
          name: firetracker-db
          property: name
      - key: DB_USER
        fromDatabase:
          name: firetracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: firetracker-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: firetracker-db
          property: host